# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-13]
        include:
          - os: windows-latest
            dest_dir: win64-${{ github.sha }}
          - os: ubuntu-22.04
            dest_dir: ubuntu-${{ github.sha }}
          - os: macos-13
            dest_dir: macos-${{ github.sha }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set environment
        shell: bash
        run: |
          echo 'DEST_DIR=${{ github.workspace }}/${{ matrix.dest_dir }}' >> $GITHUB_ENV
          
      - name: Set MACOSX_DEPLOYMENT_TARGET
        if: runner.os == 'macOS'
        run: |
          echo 'MACOSX_DEPLOYMENT_TARGET=14.0' >> $GITHUB_ENV

      - name: (Windows) Build luajit and luarocks
        if: matrix.os == 'windows-latest'
        run: |
          python hererocks.py ${{ env.DEST_DIR }} --target vs -j `@v2.1 -rlatest --verbose
          ${{ env.DEST_DIR }}/bin/luarocks.bat install inspect
          ${{ env.DEST_DIR }}/bin/luarocks.bat install luasocket
          ${{ env.DEST_DIR }}/bin/luarocks.bat install rxi-json-lua
          ${{ env.DEST_DIR }}/bin/luarocks.bat install penlight
          
      - name: (Ubuntu & MacOS) Build luajit and luarocks
        if: matrix.os != 'windows-latest'
        run: |
          python hererocks.py ${{ env.DEST_DIR }} -j @v2.1 -rlatest --verbose
          ${{ env.DEST_DIR }}/bin/luarocks install inspect
          ${{ env.DEST_DIR }}/bin/luarocks install luasocket
          ${{ env.DEST_DIR }}/bin/luarocks install luaposix
          ${{ env.DEST_DIR }}/bin/luarocks install rxi-json-lua
          ${{ env.DEST_DIR }}/bin/luarocks install penlight
          chmod +x ${{ env.DEST_DIR }}/bin/lua

      - name: Test the installation
        run: |
          cd ${{ env.DEST_DIR }}/bin
          ./lua ${{ github.workspace }}/.github/workflows/test-installation.lua

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}_dir
          path: ${{ env.DEST_DIR }}

  publish-nightly:
    name: Publish Nightly
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: Nightly # This may also be of the form 'refs/tags/staging'
          assets: '*'
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Check
        shell: bash
        run: |
          tar -C ubuntu-latest_dir -czf ubuntu-latest.tar.gz .
          tar -C windows-latest_dir -czf windows-latest.tar.gz .
          tar -C macos-13_dir -czf macos-13.tar.gz .
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.tar.gz'
          tag: Nightly
          overwrite: true
          file_glob: true
