# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux:
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            dest_dir: win64-${{ github.sha }}
        #os: [ubuntu-latest, windows-latest, macos-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set things
        run: |
          echo 'DEST_DIR=$(pwd)/${{ matrix.dest_dir }}' >> $GITHUB_ENV
          
      - name: Set MACOSX_DEPLOYMENT_TARGET
        if: runner.os == 'macOS'
        run: |
          echo 'MACOSX_DEPLOYMENT_TARGET=14.0' >> $GITHUB_ENV

      - name: (Windows) Build luajit and luarocks
        if: matrix.os == 'windows-latest'
        run: |
          python hererocks.py ${{ env.DEST_DIR }} --target vs -j `@v2.1 -rlatest --verbose
          ${{ env.DEST_DIR }}/bin/luarocks.bat install inspect
          ${{ env.DEST_DIR }}/bin/luarocks.bat install luasocket
          ${{ env.DEST_DIR }}/bin/luarocks.bat install rxi-json-lua
          
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64_dir
          path: ./x86_64_dir/
